beerfactory/hbmqtt

hbmqtt/mqtt/protocol/client_handler.py
While testing hbmqtt with the ``test.mosquitto.org`` public server and my own local installation of the Mosquitto broker showed that the hbmqtt ``MQTTClient`` would consistently disconnect and then reconnect. 
This problem appears to be caused by the ``_ping_task`` attribute never being cleared. This prevents any further Ping messages being sent, which eventually triggers a disconnection and then a subsequent reconnect.
The modification in this pull request resolves the problem, which leaves the client connected to the server and sending a ping message at the keep alive interval.
=> Fix ping issue

MANIFEST.in, setup.py
I found that when installing the hbmqtt package using setup.py, the auto created scripts hbmqtt, hbmqtt_pub & hbmqtt_sub throw an error that the default yaml filesdo not exist in the scripts directory. This small change to the setup.py will copy default_broker.yaml & default_client.yaml to the python env scripts directory.
=> Install default yaml files in scripts directory

hbmqtt/broker.py
the config flag "ssl" must be a string (on / off).  I like to suggest it should also accept a boolean.
The example uses a yaml config.  Since parsing "on" [0] in yaml returns a boolean using the example config results in an error.
[0] http://yaml.org/type/bool.html
=> accept boolean as config argument for "ssl"

docs/references/broker.rst
two simple changes
* the example code is not working as the `broker_coro` is referenced as `test_coro`
* the config tries to bind several listeners on the same port which results in errors
=> cleanup broker reference

hbmqtt/client.py
This allows a client to disable verification of the server hostname in the server certificate.
It's the same as '--insecure' option provided by mosquitto_sub.
To use it, in **default_client.yaml**:
> check_hostname: false
=> disables verification of the server hostname in the server certificate

hbmqtt/plugins/manager.py
_fire_events are only released when a plugin is closed. A long-running application will see memory usage keep growing.
I'd propose to release _fire_events that are done whenever more events are going to be added.
=> release PluginManager._fired_events if they are done

.gitignore, MANIFEST.in, tox.ini
- Included tests, examples, etc in MANIFEST.in.
- Made git ignore files that should not be included in the package.
- Added tox test environment which runs check-manifest to validate the
MANIFEST.in file.
Downstreams like Debian prefer the PyPI packages to include everything
from the Git repo, especially changelogs and test suites. To make the
installation with pip as lightweight as possible, it is encouraged to
build and upload Python wheels in addition to the sdist tarball.
The test suite currently included in the PyPI release is incomplete and thus
fails when building the Debian package. With this PR merged and released
the Debian package should be able to run the test suite automatically when
built.
=> Include all files in the PyPI releases

.travis.yml, requirements.txt, tox.ini
This modifies the Tox and Travis CI setup to run tests on all supported Python versions locally with `tox` and at Travis CI.
As the `requirements.txt` contained the same set of dependencies as `setup.py`, which is used by both Tox and Travis through Tox, it was redundant and was removed.
See commit messages for details.
=> Run test on all supported Python versions

hbmqtt/mqtt/connect.py, hbmqtt/mqtt/protocol/broker_handler.py, tests/mqtt/test_connect.py, tests/test_broker.py, tests/test_client.py
By adding a additional variable 'client_id_is_random' the Test 'test_client_connect_clean_session_false' is fixed.  This variable allows to notice if a client_id is generated by the broker( It is allowed for clients to connects with no or empty client_id). 
In this case a it is not possible for clients to use old sessions and the broker disallows a connection. (He can't identify old sessions based on the random client_id)
=> fixed Test 'test_client_connect_clean_session_false' 

hbmqtt/client.py
`deliver_task` will raise a `ClientException` to signal a connection loss. Passing it on to the caller instead of silently ignoring it lets the caller handle the connection loss. Exiting the function early also avoids an `IndexError` when trying to pop from `client_tasks`.
Fixes #106
=> Re-raise exception from deliver_task in MQTTClient.deliver_message().

hbmqtt/broker.py
With this little change, when a client is not able to authenticate, the connection will be deleted from the list of connection. In that way, it will not occupy one connection, in case the number of maximum connections is very low.
=> Client authentication error fixed

hbmqtt/broker.py, hbmqtt/plugins/topic_checking.py, samples/broker_taboo.py, samples/client_publish_taboo.py, samples/client_subscribe_taboo.py, setup.py
I have developed a new version of HBMQTT which supports topic filtering. This is: you can define a topic filtering plugin in order to grant or deny subscriptions to certain topics, depending on the policy you want.
For that, I have created the `hbmqtt/plugins/topic_checking.py` file, where I developed a very silly topic filtering policy: If you want to subscribe to `prohibited`, `top-secret` or `data/classified` topics, your username must be `admin`. Otherwise, you will not be subscribed. You may take this example as a template for designing your own topic policy.
After downloading this fork, execute the following python commands on the hbmqtt directory:
```
python3 setup.py build
python3 setup.py install
```
You can notice that this commit also adds a line in this script: This is …
=> Added topic filtering Plugin

hbmqtt/broker.py
Zero-length client_ids in CONNECT packets show up in the payload as empty strings, not None.
The broker should handle these correctly by generating its own client id as per the MQTT spec.
(This was causing some problems in Home Assistant, esp. when working with the Eclipse Paho python client, which defaults to an empty client_id.)
=> Correctly handle CONNECT with zero-length client_id

hbmqtt/client.py
Import InvalidHandshake from 'websockets.exceptions' not 'websockets.handshake', since websockets 5.0 no longer provides that alias.
=> In support of websockets 5.0

.travis.yml
Reenable the nightly build, but use Travis' support for jobs that are allowed to fail without failing the entire build.
=> Nightly build

hbmqtt/broker.py
For now broker can't verify client's certificate since CA params from config are not passed into it's SSL context.
=> Pass CA params to broker's SSL context

.travis.yml, hbmqtt/broker.py, hbmqtt/client.py, hbmqtt/mqtt/protocol/client_handler.py, hbmqtt/mqtt/protocol/handler.py, hbmqtt/plugins/manager.py, hbmqtt/plugins/sys/broker.py, scripts/pub_script.py, tests/test_broker.py, tox.ini
This will fix usage of `hbmqtt` on python3.7 (`async` now being a reserved python keyword).
The `asyncio.ensure_future` method already exists in python3.4.4 so the `asyncio.async` method should not be necessary anymore.
=> python3.7 support

hbmqtt/client.py
Global defaults are modified when creating a client with config.
=> MQTTClient: init should not overwrite global defaults

hbmqtt/client.py, tests/test_client.py
Currently if the broker_url contains username/password for `ws` and `wss`, the username and password are saved to `session.username` and `session.password`  from parsing the broker_url. 
However, the  the session.broker_uri is re-constructed for `ws` and `wss` and loses the username/password from the original broker_url. So on reconnect(), it'd attempt to connect to the broker without username/password making it fail.
This change is to make sure we don't override `session.username` and `session.password` if they already has values so that the reconnect() works as expected.
=> Only setting session username/password if it is not already set. 

hbmqtt/client.py
For a broker that required authentication using a bearer token (oauth2), I needed to send an "Authorization: Bearer <token>" header. I didn't find a way to do this with this library, so I suggest adding the possibility to specify additional headers for a websocket connection. It is quite an easy fix.
An example on how to use this could be
```
token = "abc123"
C = MQTTClient()
yield from C.connect('wss://my.domain',extra_headers={'Authorization': 'Bearer %s' % token})
```
=> passthrough of websocket extra headers

docs/references/broker.rst, hbmqtt/plugins/topic_checking.py, samples/boker_acl.py, samples/broker_acl.py, samples/client_publish_acl.py, samples/client_subscribe_acl.py, scripts/broker_script.py, scripts/default_broker.yaml, setup.py
I introduced a new topic checking plugin that implements an Access Control List (ACL) for the broker to be able to grant or deny access to clients depending on their username.
* `hbmqtt/samples/broker_acl.py` starts an MQTT broker that only allows to clients with username `test` to subscribe to the topics `['repositories/+/master', 'calendar/#', 'data/memes']`
* `hbmqtt/samples/client_subscribe_acl.py` implements an MQTT client that subscribes to the following topics:
```
yield from C.subscribe([
('data/memes', QOS_1),  # Topic allowed
('data/classified', QOS_1),  # Topic forbidden
('repositories/hbmqtt/master', QOS_1),  # Topic allowed
('repositories/hbmqtt/devel', QOS_1),  # Topic forbidden
('calendar/hbmqtt/releases', QOS_1),  # Topic allowed
])
```
* …
=> Access Control List and documentation for topic checking

hbmqtt/client.py
Fix for: #161 
Passed through `ack_timeout` param from publish method in client.py for enabling user to choose an ack timeout.
=> Fixed missing `ack_timeout` param in publish() method

docs/references/hbmqtt_pub.rst, docs/references/hbmqtt_sub.rst, docs/references/mqttclient.rst, hbmqtt/client.py
It simplifies reconnection logic. In case of long running services which publish data to server,
there is need to reconnect anyway. When reconnect_retries elapses, then reconnection have to be
done manually. Carrying about it inside coroutine which publishing data introduces complexity.
=> Add option for infitie reconnecting.

hbmqtt/client.py
This small bug probably doesn't trigger too often, which is probably also why it had been missed.
=> do actually wait for the connection in the mqtt_connection decorator

hbmqtt/client.py
We should cleanup all pending events.
=> hbmqtt.client: fix a Task leak

hbmqtt/utils.py
Since PyYAML v5.1 a warning on deprecation is printed:
> YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated,
> as the default Loader is unsafe. Please read https://msg.pyyaml.org/load
> for full details.
Use the `FullLoader`s suggared variant `yaml.full_load` according to the
documentation [1] if it's present. Then it's assumed that PyYAML >= v5.1 is
used.
[1] https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation#how-to-disable-the-warning
=> fix PyYAML warning on call of `yaml.load(…)`

hbmqtt/broker.py
Enabled 'reuse_address' by default. On Unix, this is automatically set to True anyways (see the [docs](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server)) so we can set it explicitly for Windows platforms as well.
This enables us to use `hbmqtt` in tests on Windows, without having to make up random listen addresses for each test.
I have another commit that makes this a configuration option, but I believe this implementation has much less impact.
=> Enable reuse_address by default.

hbmqtt/adapters.py
I was getting this error when trying to connect via websockets, but not TCP.
```
.../venv/lib/python3.7/site-packages/websockets/server.py:193 Error in connection handler Traceback (most recent call last):
File ".../venv/lib/python3.7/site-packages/websockets/server.py", line 191, in handler
await self.ws_handler(self, path)
File ".../venv/lib/python3.7/site-packages/hbmqtt/broker.py", line 340, in ws_connected
yield from self.client_connected(listener_name, WebSocketsReader(websocket), WebSocketsWriter(websocket))
File ".../venv/lib/python3.7/site-packages/hbmqtt/broker.py", line 354, in client_connected
remote_address, remote_port = writer.get_peer_info()
File ".../venv/lib/python3.7/site-packages/hbmqtt/adapters.py", line 124, in get_peer_info
extra_info = …
```
=> Getting peer address with self._protocol.remote_address in WebSocketsWriter

hbmqtt/adapters.py, hbmqtt/broker.py, hbmqtt/client.py, hbmqtt/codecs.py, hbmqtt/mqtt/protocol/handler.py, hbmqtt/plugins/manager.py
Critical correction for unlimited memory consumption building up retained messages for disconnected sessions where QOS is 0. I did not correct the rest of the retained message handling in this go 'round; e.g., messages should be uniquely retained by topic yet every single message is retained. Perhaps someone else will tackle this.
Critical bug fixes for client disconnect calling a deprecated asyncio API where set_exception is no longer supported on tasks. Changed to merely cancel incomplete tasks.
Critical crash fixes for log messages that were invalid due to a race condition when a session handler is detached which forces session references to None.
Added several if self.logger.isEnabledFor(logging.DEBUG): wrappers to improve performance a tiny bit. More could be done here.
=> Misc fixes
